src/v2.1/Netnr.ResponseFramework.Net4/Netnr.ResponseFramework/Controllers/InlayController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web.Mvc;
using Netnr.Data;
using Netnr.Domain;
using Netnr.Func.ViewModel;
using Newtonsoft.Json.Linq;

namespace Netnr.ResponseFramework.Controllers
{
    public class InlayController : Controller
    {
        #region 局部视图
        [Description("按钮局部视图")]
        [AllowAnonymous]
        public ActionResult Button(string current_url)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return new EmptyResult();
            }

            //按钮列表
            var listBtn = new List<SysButton>();

            //根据路由反查页面对应的菜单
            var moMenu = Func.Common.QuerySysMenuList(x => x.Url == current_url).FirstOrDefault();
            if (moMenu != null)
            {
                //登录用户的角色信息
                var luri = Func.Common.LoginUserRoleInfo();
                if (luri != null && !string.IsNullOrWhiteSpace(luri.Buttons))
                {
                    //角色配置的按钮
                    var joRole = JObject.Parse(luri.Buttons);
                    //根据菜单ID取对应的按钮
                    string btns = joRole[moMenu.Id].ToStringOrEmpty();
                    if (!string.IsNullOrWhiteSpace(btns))
                    {
                        var btnids = btns.Split(',').ToList();

                        //根据按钮ID取按钮
                        listBtn = Func.Common.QuerySysButtonList(x => btnids.Contains(x.Id)).ToList();
                    }
                }
            }

            return View(listBtn);
        }

        /// <summary>
        /// 模态框表单组件
        /// </summary>
        /// <param name="tablename">列配置表名</param>
        /// <param name="paneltitle">面板标题（有两个区域或以上时，英文逗号分隔）</param>
        /// <param name="modalsize">模态框大小 1小 2中 3大</param>
        /// <param name="index">表单ID后缀</param>
        /// <returns></returns>
        [Description("表单局部视图")]
        public ActionResult Form(string tablename, string paneltitle = "", int modalsize = 3, int index = 1)
        {
            using (var ru = new ContextBase())
            {
                //查询表对应的表单，排序，按区域分组
                var listCol = ru.SysTableConfig.Where(x => x.TableName == tablename).OrderBy(x => x.FormOrder).ToList();

                var groupCol = listCol.GroupBy(x => x.FormArea.Value).ToList();

                //表名
                TempData["tablename"] = tablename;
                //ID索引
                TempData["index"] = index;
                //模态框大小
                TempData["modalsize"] = modalsize == 3 ? "modal-lg" : modalsize == 1 ? "modal-sm" : "";
                //多面板标题
                TempData["paneltitle"] = paneltitle.Split(',').ToList();

                return View(groupCol);
            }
        }
        #endregion

        #region 配置表格

        [Description("查询配置表格")]
        public string QueryConfigTable(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();

            using (var db = new ContextBase())
            {
                var query = db.SysTableConfig;
                Func.Common.QueryJoin(query, param, db, ref or);
            }
            return or.ToJson();
        }

        [Description("保存配置表格")]
        public string SaveConfigTable(string rows, string tablename)
        {
            JArray ja = JArray.Parse(rows);

            using (var db = new ContextBase())
            {
                var listRow = db.SysTableConfig.Where(x => x.TableName == tablename).ToList();

                int order = 0;
                foreach (JToken jt in ja)
                {
                    string id = jt["Id"].ToString();

                    var mo = listRow.Where(x => x.Id == id).FirstOrDefault();

                    mo.ColTitle = jt["ColTitle"].ToStringOrEmpty();
                    mo.ColAlign = string.IsNullOrWhiteSpace(jt["ColAlign"].ToStringOrEmpty()) ? 1 : Convert.ToInt32(jt["ColAlign"].ToStringOrEmpty());
                    mo.ColWidth = string.IsNullOrWhiteSpace(jt["ColWidth"].ToStringOrEmpty()) ? 0 : Convert.ToInt32(jt["ColWidth"].ToStringOrEmpty());
                    mo.ColHide = string.IsNullOrWhiteSpace(jt["ColHide"].ToStringOrEmpty()) ? 0 : Convert.ToInt32(jt["ColHide"].ToStringOrEmpty());
                    mo.ColFrozen = string.IsNullOrWhiteSpace(jt["ColFrozen"].ToStringOrEmpty()) ? 0 : Convert.ToInt32(jt["ColFrozen"].ToStringOrEmpty());
                    mo.ColExport = string.IsNullOrWhiteSpace(jt["ColExport"].ToStringOrEmpty()) ? 0 : Convert.ToInt32(jt["ColExport"].ToStringOrEmpty());
                    mo.ColOrder = order++;
                }

                db.SysTableConfig.UpdateRange(listRow, db);
                int num = db.SaveChanges();

                return num >= 0 ? "success" : "fail";
            }
        }

        #endregion

        #region 配置表单

        [Description("保存配置表单")]
        public string SaveConfigForm(string rows, string tablename)
        {
            JArray ja = JArray.Parse(rows);

            using (var db = new ContextBase())
            {
                var listRow = db.SysTableConfig.Where(x => x.TableName == tablename).ToList();

                int order = 0;
                foreach (JToken jt in ja)
                {
                    string field = jt["field"].ToStringOrEmpty();
                    var mo = listRow.Where(x => x.ColField == field).FirstOrDefault();

                    mo.ColTitle = jt["title"].ToStringOrEmpty();
                    mo.FormSpan = string.IsNullOrWhiteSpace(jt["span"].ToStringOrEmpty()) ? 1 : Convert.ToInt32(jt["span"].ToStringOrEmpty());
                    mo.FormArea = string.IsNullOrWhiteSpace(jt["area"].ToStringOrEmpty()) ? 0 : Convert.ToInt32(jt["area"].ToStringOrEmpty());
                    mo.FormOrder = order++;
                }

                db.SysTableConfig.UpdateRange(listRow, db);
                int num = db.SaveChanges();

                return num >= 0 ? "success" : "fail";
            }
        }
        #endregion
    }
}

src/v2.1/Netnr.ResponseFramework.Net4/Netnr.ResponseFramework/Controllers/RFController.cs
using System.ComponentModel;
using System.Linq;
using System.Web.Mvc;
using Netnr.Data;
using Netnr.Func.ViewModel;

namespace Netnr.ResponseFramework.Controllers
{
    public class RFController : Controller
    {
        [Description("表配置示例页面")]
        public ActionResult Tce()
        {
            return View();
        }

        [Description("查询表配置示例")]
        public string QueryTempExample(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();
            using (var db = new ContextBase())
            {
                var query = db.TempExample;
                Func.Common.QueryJoin(query, param, db, ref or);
            }
            return or.ToJson();
        }

        [Description("DataGrid示例页面")]
        public ActionResult DataGrid()
        {
            return View();
        }

        [Description("TreeGrid示例页面")]
        public ActionResult TreeGrid(string id)
        {
            if (!string.IsNullOrWhiteSpace(id))
            {
                using (var db = new ContextBase())
                {
                    var query = from a in db.SysMenu
                                where a.Pid == id
                                orderby a.MenuOrder
                                select new
                                {
                                    a.Id,
                                    a.Pid,
                                    a.Name,
                                    a.Url,
                                    a.MenuOrder,
                                    a.Icon,
                                    a.Status,
                                    a.MenuGroup,
                                    //查询是否有子集
                                    state = (from b in db.SysMenu where b.Pid == a.Id select b.Id).Count() > 0 ? "closed" : "open"
                                };
                    var list = query.ToList();
                    return Content(list.ToJson());
                }
            }

            return View();
        }

        [Description("查询系统菜单")]
        public string QuerySysMenu(QueryDataVM.GetParams param)
        {
            var or = new QueryDataVM.OutputResult();
            using (var db = new ContextBase())
            {
                var query = db.SysMenu;
                Func.Common.QueryJoin(query, param, db, ref or);
            }
            return or.ToJson();
        }

        [Description("PropertyGrid示例页面")]
        public ActionResult PropertyGrid()
        {
            return View();
        }

        [Description("模态框表单示例页面")]
        public ActionResult Modal()
        {
            return View();
        }

        [Description("表单示例页面")]
        public ActionResult Form()
        {
            return View();
        }
    }
}

src/v2.1/Netnr.ResponseFramework.Net4/Netnr.ResponseFramework/Views/RF/DataGrid.cshtml
@{
    ViewData["Title"] = "DataGrid";
}

@{Html.RenderPartial("_BaseViewPartial");}

src/v2.1/Netnr.ResponseFramework.Net4/Netnr.ResponseFramework/Views/RF/Ins.cshtml
@{
    ViewData["Title"] = "Ins";
}

<h2>Ins</h2>


<form class="form-horizontal formui">
    <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="form-group">
                <label class='control-label'>年月日 时分秒：@DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")</label>
                <div>
                    <input type="text" id="txt1" class="form-control">
                    <i class="fa fa-clock-o form-control-feedback"></i>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="form-group">
                <label class='control-label'>年月日：@DateTime.Now.ToString("yyyy-MM-dd")</label>
                <div>
                    <input type="text" id="txt2" class="form-control">
                    <i class="fa fa-clock-o form-control-feedback"></i>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="form-group">
                <label class='control-label'>时分秒：@DateTime.Now.ToString("HH:mm:ss")</label>
                <div>
                    <input type="text" class="form-control" id="txt3">
                    <i class="fa fa-clock-o form-control-feedback"></i>
                </div>
            </div>
        </div>
    </div>
</form>

<hr />

<script>

    $('#txt1').parent().datetimepicker({
        format: "yyyy-MM-dd HH:mm:ss",
        orientation: "left"
    });

    $('#txt2').parent().datetimepicker({
        format: "yyyy-MM-dd",
        orientation: "left",
        pickTime: false
    });

    $('#txt3').parent().datetimepicker({
        format: "HH:mm:ss",
        orientation: "left",
        pickDate: false
    });


    //var locale = function () {
    //    return {
    //        applyLabel: "确定",
    //        cancelLabel: "取消",
    //        format: "YYYY-MM-DD HH:mm:ss",
    //        separator: " - ",
    //        daysOfWeek: ["日", "一", "二", "三", "四", "五", "六"],
    //        monthNames: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"]
    //    }
    //};

    ////年月日 时分秒
    //var locale1 = locale();
    //$("#txt1").daterangepicker({
    //    locale: locale1,
    //    singleDatePicker: true,
    //    showDropdowns: true,
    //    autoUpdateInput: false,
    //    timePicker24Hour: true,
    //    //autoApply: true,
    //    timePicker: true,
    //    timePickerSeconds: true
    //}).on('cancel.daterangepicker', function (ev, picker) {
    //    //取消事件
    //}).on('apply.daterangepicker', function (ev, picker) {
    //    //确定事件
    //    this.value = picker.startDate.format(locale1.format);
    //});

    ////年月日
    //var locale2 = locale();
    //locale2.format = "YYYY-MM-DD";
    //$("#txt2").daterangepicker({
    //    locale: locale2,
    //    singleDatePicker: true,
    //    showDropdowns: true
    //});

    ////时分秒
    //var locale3 = locale();
    //locale3.format = "HH:mm:ss";
    //$("#txt3").daterangepicker({
    //    locale: locale3,
    //    singleDatePicker: true,
    //    timePicker: true,
    //});

</script>

src/v2.1/Netnr.ResponseFramework.Net4/Netnr.ResponseFramework/Views/RF/PropertyGrid.cshtml
@{
    ViewData["Title"] = "PropertyGrid";
}

@{Html.RenderPartial("_BaseViewPartial");}

src/v2.1/Netnr.ResponseFramework.Net4/Netnr.ResponseFramework/Views/RF/Tce.cshtml
@{
    ViewData["Title"] = "表配置示例";
}

@{Html.RenderAction("Form", "Inlay", new { tablename = "TempExample", modalsize = 3, paneltitle = "面板一,面板二" });}

@{ Html.RenderPartial("_BaseViewPartial");}

src/v2.1/Netnr.ResponseFramework.Net4/Netnr.ResponseFramework/Views/RF/TreeGrid.cshtml
@{
    ViewData["Title"] = "TreeGrid";
}

@{Html.RenderPartial("_BaseViewPartial");}